### ISSUE TITLE
Error when attempting rename

### ISSUE THREAD

**Issue by randycoulman** [gp-pereira/refactorex#14]
Thanks so much for this long-awaited tool! I'm going to open a few issues based on my early usage of RefactorEx, but please know that I'm extremely grateful for all of your work on this so far!

In [this file from one of my open-source projects](https://github.com/randycoulman/mix_test_interactive/blob/main/lib/mix_test_interactive.ex), I attempted to rename the `args` parameter to `run` on line 15.

When I hit the `F2` key to start the rename, I received the error below in the RefactorEx output window in VSCode. I was still prompted for a new name, but when I entered the new name, only the two occurrences on line 15 were updated. The occurrence on line 16 was not renamed.

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a list

    :erlang.length(nil)
    (refactorex 0.1.0) lib/refactorex/refactor/function.ex:36: Refactorex.Refactor.Function.find_definitions/1
    (refactorex 0.1.0) lib/refactorex/refactor/function/rename_function.ex:20: Refactorex.Refactor.Function.RenameFunction.can_refactor?/2
    (refactorex 0.1.0) lib/refactorex/refactor/function/rename_function.ex:2: Refactorex.Refactor.Function.RenameFunction.visit/4
    (sourceror 1.0.2) lib/sourceror/zipper.ex:452: Sourceror.Zipper.do_traverse_while/3
    (refactorex 0.1.0) lib/refactorex/refactor/function/rename_function.ex:2: Refactorex.Refactor.Function.RenameFunction.available?/2
    (refactorex 0.1.0) lib/refactorex/refactor.ex:112: anonymous fn/3 in Refactorex.Refactor.available_refactorings/3
    (elixir 1.17.2) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
```

**Comment by gp-pereira** [comment]
Hi there

So, the problem you encountered was caused by the way I was initially searching for the variable and replacing it, which was kinda naive. Now I've implemented a more robust dataflow analysis algorithm to connect all variable references. I've also tested on the examples you provided and it's working correctly in v0.1.32. You can also rename from an usage now as well. I hope that this refactoring is way more reliable after these changes. 

I still havent solved the above error on rename_function though, but will do it soon
