### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by nallwhy** [gp-pereira/refactorex#5]
mac, asdf

```
[Error - 8:46:38 AM] Refactorex client: couldn't create connection to server.
Error: Compilation error: ** (File.Error) could not remove files and directories recursively from "/Users/username/vscode/extensions/gp-pereira.refatorex-0.1.24/refactorex/deps/credo": file already exists
    (elixir 1.17.1) lib/file.ex:1388: File.rm_rf!/1
    (hex 2.1.1) lib/hex/scm.ex:169: Hex.SCM.update/1
    (mix 1.17.1) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.17.1) lib/mix/dep/converger.ex:238: Mix.Dep.Converger.all/9
    (mix 1.17.1) lib/mix/dep/converger.ex:254: Mix.Dep.Converger.all/9
    (mix 1.17.1) lib/mix/dep/converger.ex:170: Mix.Dep.Converger.init_all/8
    (mix 1.17.1) lib/mix/dep/converger.ex:144: Mix.Dep.Converger.all/4
    (mix 1.17.1) lib/mix/dep/converger.ex:89: Mix.Dep.Converger.converge/4
```

**Comment by gp-pereira** [comment]
it seems like it tried to install itself twice which is super weird. Can you uninstall it and `rm -rf /Users/username/vscode/extensions/gp-pereira.refatorex-0.1.24` before trying to install it again please?

**Comment by nallwhy** [comment]
After few times of reinstall, it is fixed. Thanks.
